package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        configureKeyBindings();
        configureKeyBindings();
        configureScrollBars();
        configureEditorLineNumbers();
        txtMensagens.setEditable(false);
        lblStatus.setText("Nenhum arquivo aberto"); 
    }
    
    private java.io.File arquivoAtual = null; // arquivo novo a ser salvo
    
    private void salvarArquivo(java.io.File arquivo) {
    try (java.io.BufferedWriter writer = new java.io.BufferedWriter(
            new java.io.FileWriter(arquivo))) {

        writer.write(txtEditor.getText());

        // Limpa área de mensagens
        txtMensagens.setText("");

        // Atualiza barra de status apenas se arquivo novo (caso 1)
        // No caso 2, lblStatus já está com o caminho correto — não altera
        lblStatus.setText(arquivo.getAbsolutePath());

    } catch (IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Erro ao salvar o arquivo: " + ex.getMessage(),
            "Erro",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        private void addKeyBinding(String tecla, JButton botao) {

            KeyStroke ks = KeyStroke.getKeyStroke(tecla);

            getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                    .put(ks, tecla);

            getRootPane().getActionMap().put(tecla, new AbstractAction() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    botao.doClick();
                }
            });
        }
        
        private void configureKeyBindings() {
            addKeyBinding("control N", btnNovo);
            addKeyBinding("control O", btnAbrir);
            addKeyBinding("control S", btnSalvar);
            addKeyBinding("control C", btnCopiar);
            addKeyBinding("control V", btnColar);
            addKeyBinding("control X", btnRecortar);
            addKeyBinding("F7", btnCompilar);
            addKeyBinding("F1", btnEquipe);
        }
            
        /**
         * Displays a message in the messages area of the interface.
         * This method replaces any existing content in the messages text area
         * with the provided message.
         *
         * @param message the message to be displayed in the messages area
         */
        private void showMessage(String message) {
            txtMensagens.setText(message);
        }
        
        /**
         * Clears the main components of the interface.
         * This method removes all text from the editor area, the messages area,
         * and the status bar label.
         */
        private void clean() {
            txtEditor.setText("");
            txtMensagens.setText("");
            lblStatus.setText("");
        }
        
        /**
         * Configures the scroll bar behavior for the editor and messages areas.
         * Both horizontal and vertical scroll bars are set to always be visible
         * in order to satisfy the interface requirements of the compiler.
         */
        private void configureScrollBars() {

            scrollEditor.setHorizontalScrollBarPolicy(
                    JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS
            );

            scrollEditor.setVerticalScrollBarPolicy(
                    JScrollPane.VERTICAL_SCROLLBAR_ALWAYS
            );

            scrollMensagens.setHorizontalScrollBarPolicy(
                    JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS
            );

            scrollMensagens.setVerticalScrollBarPolicy(
                    JScrollPane.VERTICAL_SCROLLBAR_ALWAYS
            );
        }
        
        /**
         * Configures the line numbering feature for the editor area.
         * A secondary text area is used as a row header of the editor scroll pane
         * to display line numbers. A document listener monitors changes in the
         * editor content and updates the line numbers dynamically whenever text
         * is inserted, removed, or modified.
         */
        private void configureEditorLineNumbers() {

            JTextArea lineNumbers = new JTextArea("1");
            lineNumbers.setEditable(false);
            lineNumbers.setForeground(new java.awt.Color(80, 80, 80));
            lineNumbers.setBackground(new Color(230,230,230));

            scrollEditor.setRowHeaderView(lineNumbers);

            txtEditor.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

                private String getText() {
                    int linhas = txtEditor.getLineCount();
                    StringBuilder text = new StringBuilder("1");

                    for (int i = 2; i <= linhas; i++) {
                        text.append("\n").append(i);
                    }

                    return text.toString();
                }

                @Override
                public void insertUpdate(javax.swing.event.DocumentEvent e) {
                    lineNumbers.setText(getText());
                }

                @Override
                public void removeUpdate(javax.swing.event.DocumentEvent e) {
                    lineNumbers.setText(getText());
                }

                @Override
                public void changedUpdate(javax.swing.event.DocumentEvent e) {
                    lineNumbers.setText(getText());
                }
            });
        }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();
        btnColar = new javax.swing.JButton();
        btnRecortar = new javax.swing.JButton();
        btnCompilar = new javax.swing.JButton();
        btnEquipe = new javax.swing.JButton();
        splitEditorMensagens = new javax.swing.JSplitPane();
        scrollEditor = new javax.swing.JScrollPane();
        txtEditor = new javax.swing.JTextArea();
        scrollMensagens = new javax.swing.JScrollPane();
        txtMensagens = new javax.swing.JTextArea();
        panelStatus = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        toolBar.setRollover(true);
        toolBar.setMaximumSize(new java.awt.Dimension(1490, 70));
        toolBar.setPreferredSize(new java.awt.Dimension(1500, 70));

        btnNovo.setIcon(new javax.swing.ImageIcon("./src/resources/assets/icons/new-icon.png"));
        btnNovo.setText(" novo [ctrl-n]");
        btnNovo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setMargin(new java.awt.Insets(4, 14, 3, 14));
        btnNovo.setMaximumSize(new java.awt.Dimension(120, 60));
        btnNovo.setPreferredSize(new java.awt.Dimension(120, 60));
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        toolBar.add(btnNovo);

        btnAbrir.setIcon(new javax.swing.ImageIcon("./src/resources/assets/icons/open-file-icon.png")); // NOI18N
        btnAbrir.setText("abrir [ctrl-o]");
        btnAbrir.setAutoscrolls(true);
        btnAbrir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setMaximumSize(new java.awt.Dimension(120, 60));
        btnAbrir.setPreferredSize(new java.awt.Dimension(120, 60));
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        toolBar.add(btnAbrir);

        btnSalvar.setIcon(new javax.swing.ImageIcon("./src/resources/assets/icons/save-icon.png")); // NOI18N
        btnSalvar.setText("salvar [ctrl-s]");
        btnSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setMaximumSize(new java.awt.Dimension(120, 60));
        btnSalvar.setPreferredSize(new java.awt.Dimension(120, 60));
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        toolBar.add(btnSalvar);

        btnCopiar.setIcon(new javax.swing.ImageIcon("./src/resources/assets/icons/copy-icon.png"));
        btnCopiar.setText("copiar [ctrl-c]");
        btnCopiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCopiar.setFocusable(false);
        btnCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCopiar.setMaximumSize(new java.awt.Dimension(120, 60));
        btnCopiar.setPreferredSize(new java.awt.Dimension(120, 60));
        btnCopiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });
        toolBar.add(btnCopiar);

        btnColar.setIcon(new javax.swing.ImageIcon("./src/resources/assets/icons/paste-icon.png"));
        btnColar.setText("colar  [ctrl-v]");
        btnColar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnColar.setFocusable(false);
        btnColar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnColar.setMaximumSize(new java.awt.Dimension(120, 60));
        btnColar.setPreferredSize(new java.awt.Dimension(120, 60));
        btnColar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColarActionPerformed(evt);
            }
        });
        toolBar.add(btnColar);

        btnRecortar.setIcon(new javax.swing.ImageIcon("./src/resources/assets/icons/icons8-cut-24.png"));
        btnRecortar.setText("recortar [ctrl-x]");
        btnRecortar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRecortar.setFocusable(false);
        btnRecortar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecortar.setMaximumSize(new java.awt.Dimension(120, 60));
        btnRecortar.setPreferredSize(new java.awt.Dimension(120, 60));
        btnRecortar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecortarActionPerformed(evt);
            }
        });
        toolBar.add(btnRecortar);

        btnCompilar.setIcon(new javax.swing.ImageIcon("./src/resources/assets/icons/icons8-play-24.png"));
        btnCompilar.setText("compilar [F7]");
        btnCompilar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCompilar.setFocusable(false);
        btnCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompilar.setMaximumSize(new java.awt.Dimension(120, 60));
        btnCompilar.setPreferredSize(new java.awt.Dimension(120, 60));
        btnCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarActionPerformed(evt);
            }
        });
        toolBar.add(btnCompilar);

        
        btnEquipe.setIcon(new javax.swing.ImageIcon("./src/resources/assets/icons/team-icon.png"));
        btnEquipe.setText(" equipe [F1]");
        btnEquipe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEquipe.setFocusable(false);
        btnEquipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEquipe.setMaximumSize(new java.awt.Dimension(120, 60));
        btnEquipe.setPreferredSize(new java.awt.Dimension(120, 60));
        btnEquipe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipeActionPerformed(evt);
            }
        });
        toolBar.add(btnEquipe);

        splitEditorMensagens.setDividerLocation(400);
        splitEditorMensagens.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitEditorMensagens.setPreferredSize(new java.awt.Dimension(1500, 680));
        splitEditorMensagens.setVerifyInputWhenFocusTarget(false);

        txtEditor.setColumns(20);
        txtEditor.setRows(5);
        scrollEditor.setViewportView(txtEditor);

        splitEditorMensagens.setTopComponent(scrollEditor);

        txtMensagens.setColumns(20);
        txtMensagens.setRows(5);
        scrollMensagens.setViewportView(txtMensagens);

        splitEditorMensagens.setRightComponent(scrollMensagens);

        panelStatus.setPreferredSize(new java.awt.Dimension(1500, 25));

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatus)
                .addContainerGap(1494, Short.MAX_VALUE))
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatusLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(lblStatus))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(splitEditorMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitEditorMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        clean();
        arquivoAtual = null;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        showMessage("Compilação de programas ainda não foi implementada");
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void btnEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipeActionPerformed
        showMessage("Equipe: Júlia Passos e Rafael Carvalho");
    }//GEN-LAST:event_btnEquipeActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        JFileChooser fileChooser = new JFileChooser();

    FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "Arquivos de texto (*.txt)", "txt"
    );
    fileChooser.setFileFilter(filter);
    fileChooser.setAcceptAllFileFilterUsed(false);

    int resultado = fileChooser.showOpenDialog(this);

    if (resultado == JFileChooser.APPROVE_OPTION) {
        java.io.File arquivo = fileChooser.getSelectedFile();
        arquivoAtual = arquivo;

        try (BufferedReader reader = new BufferedReader(
                new FileReader(arquivo))) {

            StringBuilder conteudo = new StringBuilder();
            String linha;

            while ((linha = reader.readLine()) != null) {
                conteudo.append(linha).append("\n");
            }

            txtEditor.setText(conteudo.toString());
            txtMensagens.setText("");
            lblStatus.setText(arquivo.getAbsolutePath());

        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao ler o arquivo: " + ex.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (arquivoAtual == null) {
        // (1) Arquivo novo — abre diálogo para escolher pasta/nome
        JFileChooser fileChooser = new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Arquivos de texto (*.txt)", "txt"
        );
        fileChooser.setFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            java.io.File arquivo = fileChooser.getSelectedFile();

            // Garante a extensão .txt
            if (!arquivo.getName().toLowerCase().endsWith(".txt")) {
                arquivo = new java.io.File(arquivo.getAbsolutePath() + ".txt");
            }

            arquivoAtual = arquivo; // guarda referência para próximos salvamentos
            salvarArquivo(arquivoAtual);
        }
        // Se cancelou: não faz nada

    } else {
        // (2) Arquivo já existe — salva direto sem abrir diálogo
        salvarArquivo(arquivoAtual);
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        txtEditor.copy();
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnColarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColarActionPerformed
        txtEditor.paste();
    }//GEN-LAST:event_btnColarActionPerformed

    private void btnRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecortarActionPerformed
        txtEditor.cut();
    }//GEN-LAST:event_btnRecortarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName()
            );
        } catch (Exception e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnColar;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnEquipe;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRecortar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JScrollPane scrollEditor;
    private javax.swing.JScrollPane scrollMensagens;
    private javax.swing.JSplitPane splitEditorMensagens;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JTextArea txtEditor;
    private javax.swing.JTextArea txtMensagens;
    // End of variables declaration//GEN-END:variables
}